name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install dependencies and run tests
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # Run tests (if test cases are available)

      # Authenticate with Google Cloud
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure Docker to use GCR
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker

      # Build and tag the Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app:${{ github.sha }}
          docker build -f ./Dockerfile -t $IMAGE_NAME .

      # Push the Docker image to GCR
      - name: Push to GCR
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app:${{ github.sha }}
          docker push $IMAGE_NAME

      # Deploy to Cloud Run (Optional)
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-app:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
