name: Deploy to Cloud Run

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: # Enables manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install dependencies and run tests (optional)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # Run tests (if test cases are available)

      # Authenticate with Google Cloud
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure Docker to use Artifact Registry
      - name: Configure Docker for GAR
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # Build and tag the Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/flask-app:${{ github.sha }}
          docker build -t $IMAGE_NAME .

      # Push the Docker image to GAR
      - name: Push to GAR
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/flask-app:${{ github.sha }}
          docker push $IMAGE_NAME

      # Deploy to Cloud Run (Optional)
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-app \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/flask-app:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
