name: Deploy to GCE

on:
  workflow_dispatch: # Enables manual trigger for deployment

jobs:
  deploy-to-gce:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (optional if configuration files are in the repo)
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: "beta" # Optional: Install additional components if needed

      # Configure Docker to authenticate with Google Cloud
      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # List and get the most recent image tag from Artifact Registry
      - name: Pull the latest Docker image from GAR
        id: pull_image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/containerized-api-deployment/my-repo/flask-app

          # List all images, filter by timestamp, sort by the most recent, and get the most recent tag
          MOST_RECENT_TAG=9d788deca9ed7b09c7105a321f6c4c844352c519
          docker pull $IMAGE_NAME:$MOST_RECENT_TAG

      # Deploy the image to GCE
      - name: Deploy to GCE
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/flask-app:9d788deca9ed7b09c7105a321f6c4c844352c519
          gcloud compute instances create-with-container gce-flask-app \
            --zone=us-central1-a \
            --machine-type=e2-medium \
            --container-image=$IMAGE_NAME \
            --tags=http-server,https-server \
            --restart-on-failure
