name: Deploy to GCE

on:
  workflow_dispatch: # Enables manual trigger for deployment

jobs:
  deploy-to-gce:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (optional if configuration files are in the repo)
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Configure Docker to authenticate with Google Cloud
      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # List and get the most recent image tag from Artifact Registry
      - name: Pull the latest Docker image from GAR
        id: pull_image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/flask-app

          # List all images, filter by timestamp, sort by the most recent, and get the most recent tag
          MOST_RECENT_TAG=$(gcloud artifacts docker images list $IMAGE_NAME \
            --sort-by="~timestamp.datetime" \
            --limit=1 \
            --format="value(tags[0])")

          # Check if a tag is found
          if [ -z "$MOST_RECENT_TAG" ]; then
            echo "No images found for the repository."
            exit 1
          else
            echo "Pulling image with tag: $MOST_RECENT_TAG"
            docker pull $IMAGE_NAME:$MOST_RECENT_TAG
            echo "most_recent_tag=$MOST_RECENT_TAG" >> $GITHUB_ENV
          fi

      # Deploy the image to GCE
      - name: Deploy to GCE
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/flask-app:${{ env.most_recent_tag }}
          gcloud compute instances create-with-container gce-flask-app \
            --zone=us-central1-a \
            --machine-type=e2-medium \
            --container-image=$IMAGE_NAME \
            --tags=http-server,https-server \
            --restart-on-failure